language: smalltalk
sudo: false

smalltalk:
  - Pharo-alpha
  - Pharo-stable
  - Pharo-4.0
  - Pharo-3.0

  - Squeak-trunk
  - Squeak-5.1
  - Squeak-5.0
  - Squeak-4.6
  - Squeak-4.5

matrix:
  allow_failures:
    - smalltalk: Squeak-trunk
    - smalltalk: Pharo-alpha
  fast_finish: true
